### ISSUE TITLE
Awesome work!

### ISSUE THREAD

**Issue by IbanezJS** [ttustonic/LightGBMSharp#1]
Hi.

A fresh project. So not issue but some questions:
1)Have you tried it on linux with netcore?
2)How to restrict LightGBM.LGBM.Train to 1 CPU core? In general how to setup number of cores
3)Is there 'feature importance' in LightGbm like in XGBoost?
4)What is the fastest way to get prediction for single row on already trained model. If say i have a stream of newcoming rows and i want to get prediction for each row as fast as possible

**Comment by ttustonic** [comment]
Hello and thanks!
1) No.
2) I think that Estimator.NumThreads should do.

as for the rest, please read <a href="https://github.com/ttustonic/LightGBMSharp/blob/master/Notice.md">this notice.</a>

**Comment by johntseng** [comment]
@ttustonic Thanks for your awesome work! This saved me a ton of time so that my app doesn't need to write the data to disk just to have lightgbm read it back again. 

@IbanezJS 
3) It does: https://github.com/ttustonic/LightGBMSharp/blob/master/LightGBM/BoosterMethods.cs#L263
Here's what the parameters mean: 
https://github.com/Microsoft/LightGBM/blob/ffeae5a660147b7b04a9e7cd399953af271a9511/src/boosting/gbdt_model_text.cpp#L468
The command line version will dump the feature importance by default.

4) The built-in way is super slow to get single row predictions. There are a few issues in the LightGBM github, but doesn't appear to have an easy solution, yet. I parse the json dump, build the trees in .NET, and then do the predictions off of there. lightgbm has a bunch of different types of splits, but I only needed to implement the `<=` split for my trees.

**Comment by IbanezJS** [comment]
@johntseng thank you for comments.

Can you share your .net code for prediction on parsed model?
I trained a single class binary classifier prediction model. 
But need to predict stream data with it very fast

**Comment by johntseng** [comment]
@IbanezJS Unfortunately, I can't.

**Comment by IbanezJS** [comment]
@johntseng Ok, then
What do you think: 
-Does it worth to 'copy pate' c++ LightGBM and create unsafe C# .netcore simple version without network partitioning? 
-And by the way XGBoost or LightGBM on you choice?

**Comment by johntseng** [comment]
@IbanezJS The prediction portion of the code is fairly straightforward. There's also a command to generate a C++ version of the model: https://github.com/Microsoft/LightGBM/blob/master/src/io/tree.cpp#L355

I haven't tried XGBoost, yet. LightGBM works pretty well for me so far. There's a .NET wrapper for XGBoost as well: https://github.com/PicNet/XGBoost.Net
